### ISSUE TITLE
Creation of a new repository for WG Charters

### ISSUE THREAD

**Issue by jpradocueva** [OpenManufacturingPlatform/rules_of_engagement#10]
https://github.com/OpenManufacturingPlatform/charters

This repository should be used to develop charters for Working Groups.

**Comment by BirgitBoss** [comment]
And where exactly is the repository for the released (template for signing) and signed WG charters? In Teams? Who has access to signed WG charters?
We should clearly state that this charter repository is not only starting as a private repository but is private to OMP members only, i.e. repository remains private.

The WG charter is no document that is maintained, although some iterations are needed to finalize it. This is different to deliverables of a WG. The charter is no deliverable.

**Comment by jpradocueva** [comment]
the suggestion is to use a repository to develop the charters.
The signature and storage of WG charters signed by each members company should be stored some where in Teams as a pdf's. 

In other organizations the chapter is developed by the WGs and made publicly available as a way to show the scope of the WG. But companies doesn't need to sign the WG charter. In these organizations it is just ok to sign the Membership application and Project Charter and they will have access to all the WGs.

In OMP once the WG charter is formalized it must be signed by those companies that want to belong to the WG. The signed documents should be kept private but the actual WG charter template should be made publicly available. It can be used as a promotional tool to show case what the WG is doing.

**Comment by jpradocueva** [comment]
Charter repository contains now CONTRIBUTING guidelines
