### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by BirgitBoss** [OpenManufacturingPlatform/rules_of_engagement#22]
Typos
	Technical Speciications Development Phases (
		AD ==> (AD)
	Publication
	     authomatically ==> automatically
		 
		 open a via of "dialogue"  ==> ??? open a what?

**Comment by jpradocueva** [comment]
we will proofread the document while applying PRs and at the end before presented to ORG Team.

**Comment by jpradocueva** [comment]
rectified in PR #27
