### ISSUE TITLE
Split Publication & Maintenance

### ISSUE THREAD

**Issue by BirgitBoss** [OpenManufacturingPlatform/rules_of_engagement#24]
I feel we should split the process steps publication and maintenance

Unclear: SC approval needed for every minor and bugfix release. Only for major releases? For all releases?

I am not sure I read it: are we using semantic versioning 1.0.2 etc.?

**Comment by jpradocueva** [comment]
In reality the publication process and maintenance is split. 

**Publication**
* it can be done automatically by merging the content from the "development | or staging" branch into the "master" branch.

**Maintenance**
* We can request public input via GitHub Issues, straight into the repository that contains the Technical documents or code.
* The corresponding group will review the issues and based on its merits the group may create a new revision of the specifications (version x.y.z), e.g. from v1.0 to v1.0.1
* Therefore, maintenance can be consider as an extension of the development phase.

> In the image below I have added a red line to indicate that the public input is taken back into the development phase. The WG will discuss the issues or changes proposed an upon WG agreement a new version x.y.z of the specification may be created.

![image](https://user-images.githubusercontent.com/3258579/82601534-8fcf8c00-9b64-11ea-8b32-915458bb3962.png)

**Comment by jpradocueva** [comment]
@BirgitBoss I will leave the image as it is. If the above explanation is still unclear I will try to modify the diagram.
