### ISSUE TITLE
add charter template 

### ISSUE THREAD

**Issue by jpradocueva** [OpenManufacturingPlatform/rules_of_engagement#28]
PR https://github.com/OpenManufacturingPlatform/templates/pull/6 is proposing a charter template to be stored in the "templates" repo.

Any Working Group can use the charter template to create a new charter. The document could be discussed in the "charter" repo and once it is approved it can be converted into word document and send to the members companies to be signed.

Based on this simple work flow, I can add a new diagram to the README file in the "charter" repo so everyone understand the process. Then we can add a link from the "rules of engagement" to the the charter repo and to the templates repo.

Comments?

**Comment by BirgitBoss** [comment]
From my point of view: Not only WG (then everybody would need to agree in the WG accoridng to voting process in WG but I think this is not necessary) but also individual OMP members can propose a new WG. For SC approval they should be able to state which other companies would be interested to join the WG.

**Comment by jpradocueva** [comment]
A Contributing file has been created to assist with the process of creating and approving a new charter.
