### ISSUE TITLE
Working Groups

### ISSUE THREAD

**Issue by JuBac93** [OpenManufacturingPlatform/rules_of_engagement#30]
The following sentence: "Working Groups (WGs) are chartered by TSC to handle one or more work items." Currently we don't have a TSC. So I would point that to the steering committee.

**Comment by jpradocueva** [comment]
rectified in PR #27

**Comment by BirgitBoss** [comment]
Unfortunately, I am not able to see what PR #27 really covers.
What is TSC? Technical SC? 
The rules should cover both, the case where there is a TSC established (and I assume we need one - not now, but later) and if there is none the SC itself.

**Comment by jpradocueva** [comment]
TSC stands for Technical Steering Committee. 
The suggestion was to change TSC for Steering Committee (SC)
In PR #27 the commit that introduces that change is: [Commit](https://github.com/OpenManufacturingPlatform/rules_of_engagement/pull/27/commits/97c34a63d09710c081565ea0621f5bd6264b5f91)

**Comment by jpradocueva** [comment]
changes incorporated in "proposal" branch.
