### ISSUE TITLE
Working Group (Vice) Chairs, Participants & Voting

### ISSUE THREAD

**Issue by sbuckel** [OpenManufacturingPlatform/rules_of_engagement#33]
1) "Each Working Group will designate a chair for that Working Group"
-> How is the chair designated? Currently, the company that initiates the group designes the Working Group Chair.

2) "Each working Group must be comprised of at lease 2 Working Group Participants"
-> 2 participants from two different companies? 

3) How are the vice-chairs designated? Determined by the WG chair? 

4) "... working group will make that decision by a supermajority vote of the WG Participants"
-> What does supermajority mean? What is with 50/50 situations?
-> Has a company one vote or has each participant one vote? What is happening if two participants of one company want to vote differently? (-> e.g. counts as abstention?)

**Comment by BirgitBoss** [comment]
W.r.t. 3.: From other organizations I know everybody can nominate him- or herself as Co-Chair or propose somebody else. Then there are clear election rules. In practice, normally either there is no choice and everybody is happy that there is a co-chair or one of the nominees steps back. However; I think we need election rules.

W.r.t. 1.) The company or Team within OMP who is creating the charter can also nominate the chair I would say. This would be then part of the approval (or disapproval) in the SC. The SC should only decide on WG charters for which there is a designates chair (as an alterantive there might be another WG Chair who is willing to do a election process simillar to the Co-Chair election process.

W.r.t. 3) I would not could them vice-chair but co-chair. Then it is easier to nominate more than one co-chair (if needed). I know the need in some WG in other organizations... Especially in liaisons with other organizations.

W.r.t. 4) I would say every company has a vote. In 50/50 situations both might be nominated as Chair?

**Comment by sbuckel** [comment]
Thank you for your comments. Point 4 was not specifically related to the choice of chair, but to votings in general. 

The term co-chair would be okay for me. 

"The company or Team within OMP who is creating the charter can also nominate the chair I would say." -> I agree

**Comment by jpradocueva** [comment]
with regards to use co-chair instead of vice-chair.
 - [x] PRs:  PR #17 and #27 have changed the name from 'vice-chair' to 'co-chair'

with regards to: (1), (2) and (4), the paragraphs were copied from the already signed Project Charter. So far, I haven't found any statement in the Project Charter about  the threshold  definition for a supermajority. This may need to be discussed by the ORG Team and ratify by the Steering Committee.

**Comment by jpradocueva** [comment]
Changes incorporated.
