### ISSUE TITLE
Add github Public

### ISSUE THREAD

**Issue by BirgitBoss** [OpenManufacturingPlatform/rules_of_engagement#36]
I am missing github public in the overall (blue) figure (only web-site mentioned but no technical specification and no source code). 
Source code is not mentioned at all in the text.
For me source code (and not specifications) is the major contribution of OMP!

**Comment by jpradocueva** [comment]
- [ ] add GitHub landed pages and public repos to public side of OMP

**Comment by jpradocueva** [comment]
A new section can be dedicated for source code. 
A public github icon has been added to the diagram.
